export const FETCH_BESTSALES_REQUEST = 'FETCH_BESTSALES_REQUEST';
export const FETCH_BESTSALES_FAILURE = 'FETCH_BESTSALES_FAILURE';
export const FETCH_BESTSALES_SUCCESS = 'FETCH_BESTSALES_SUCCESS';

export const FETCH_CATEGORIES_REQUEST = 'FETCH_CATEGORIES_REQUEST';
export const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';

export const FETCH_DATA_CATEGORIES_REQUEST = 'FFETCH_DATA_CATEGORIES_REQUEST';
export const FETCH_DATA_CATEGORIES_FAILURE = 'FETCH_DATA_CATEGORIES_FAILURE';
export const FETCH_DATA_CATEGORIES_SUCCESS = 'FETCH_DATA_CATEGORIES_SUCCESS';

export const FIND_GOODS = 'FIND_GOODS';
export const ICON_GOODS_IN_CART = 'ICON_GOODS_IN_CART';

export const SEND_ORDER_GOODS = 'SEND_ORDER_GOODS';
export const FETCH_DATA_ORDER_SUCCESS = 'FETCH_DATA_ORDER_SUCCESS';
export const FETCH_DATA_ORDER_FAILURE = 'FETCH_DATA_ORDER_FAILURE';

